# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: buildlib
        run: |
          git clone --recurse-submodules https://github.com/stevemk14ebr/PolyHook_2_0.git .
          mkdir _build
          mkdir _install
          cmake -B"./_build" -DCMAKE_INSTALL_PREFIX="./_install/" -DPOLYHOOK_BUILD_SHARED_LIB=OFF
          cmake --build "./_build" --config Release --target install
      - name: upload
        uses: actions/upload-artifact@v3.1.0
        with: 
          name: polyhook
          path: "./_install/"
          
