# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: buildlib
        run: |
          git clone https://github.com/MolecularMatters/raw_pdb.git .
          rm build -rf
          mkdir build
          cmake --build "." --config Release
        shell: bash
      - name: upload
        uses: actions/upload-artifact@v3.1.0
        with: 
          name: raw_pdb
          path: "./src/Release/"
          
